name: RoyalCommands
main: tk.royalcraf.royalcommands.RoyalCommands
version: 0.0.5
author: jkcclemens
depend: [Vault]

commands:
  level:
    description: Levels your experience up one level.
    usage: /<command>

  setlevel:
    description: Sets your XP level to specified amount.
    usage: /<command> [level] <player>

  sci:
    description: Selectively removes items from a player's inventory.
    usage: /<command> [player] [ID]

  speak:
    description: Make another player talk.
    usage: /<command> [player] [message]

  facepalm:
    description: Broadcasts your facepalm.
    usage: /<command>

  slap:
    description: Broadcasts you slapping another player.
    usage: /<command> [player]

  harm:
    description: Harms a player.
    usage: /<command> [player] [damage]

  starve:
    description: Lowers a player's hunger.
    usage: /<command> [player] [damage]

  banned:
    description: Returns if a player is banned.
    usage: /<command> [player]
    
  setarmor:
    description: Sets your armor to a certain type.
    usage: /<command> [material]
    
  getip:
    description: Gets the IP of a user.
    usage: /<command> [player]
    
  compareip:
    description: Compare two users' IP addresses.
    usage: /<command> [player1] [player2]
  
  ragequit:
    description: Ragequits yourself or another player.
    usage: /<command> <player>
    
  quit:
    description: Makes yourself quit.
    usage: /<command>
    
  rank:
    description: Check the rank of the specified player (permissions).
    usage: /<command> [player]
    
  freeze:
    description: Freezes the player.
    usage: /<command> [player]
    
  fakeop:
    description: Fakes an "You are now op!" message.
    usage: /<command> [player]
    
  rcmds:
    description: Displays version of RoyalCommands.
    usage: /<command>
    
permissions:
  rcmds.*:
    description: Gives access to all RoyalCommands commands.
    children:
      rcmds.level: true
      rcmds.setlevel: true
      rcmds.sci: true
      rcmds.speak: true
      rcmds.facepalm: true
      rcmds.slap: true
      rcmds.harm: true
      rcmds.starve: true
      rcmds.banned: true
      rcmds.setarmor: true
      rcmds.getip: true
      rcmds.compareip: true
      rcmds.ragequit: true
      rcmds.quit: true
      rcmds.rcmds: true
  rcmds.exempt:
    description: Gives the exempt permission for every command.
    children:
      rcmds.sci.exempt: true
      rcmds.speak.exempt: true
      rcmds.facepalm.exempt: true
      rcmds.slap.exempt: true
      rcmds.harm.exempt: true
      rcmds.starve.exempt: true
  rcmds.level:
    description: Allows you to level your XP up by 1
    default: op
  rcmds.setlevel:
    description: Allows you to set your XP level
    default: op
  rcmds.sci:
    description: Allows you to selectively clear inventories
    default: op
  rcmds.speak:
    description: Allows you to spoof a message
    default: op
  rcmds.facepalm:
    description: Allows you to facepalm
    default: op
  rcmds.slap:
    description: Allows you to slap another player
    default: op
  rcmds.harm:
    description: Allows you to damage another player
    default: op
  rcmds.starve:
    description: Allows you to starve another player
    default: op
  rcmds.banned:
    description: Allows you to check if a player is banned
    default: op
  rcmds.setarmor:
    description: Allows you to set your armor
    default: op
  rcmds.getip:
    description: Allows you to get the IP of another player
    default: op
  rcmds.compareip:
    description: Allows you to compare to players' IPs
    default: op
  rcmds.ragequit:
    description: Allows you to ragequit.
    default: op
  rcmds.quit:
    description: Allows you to quit.
    default: op
  rcmds.rank:
    description: Allows you to check the rank of a player.
    default: op
  rcmds.freeze:
    description: Allows you to freeze a player.
    default: op
  rcmds.fakeop:
    description: Allows you to fake op.
    default: op
  rcmds.rcmds:
    description: Allows you to reload RoyalCommands' config
    default: op