name: RoyalCommands
main: tk.royalcraf.royalcommands.RoyalCommands
version: 0.0.7
author: jkcclemens
depend: [Vault]

commands:
  level:
    description: Levels your experience up one level.
    usage: /<command>

  setlevel:
    description: Sets your XP level to specified amount.
    usage: /<command> [level] (player)
    aliases: [slvl, slevel, setlvl]

  sci:
    description: Selectively removes items from a player's inventory.
    usage: /<command> [player] [ID]

  speak:
    description: Make another player talk.
    usage: /<command> [player] [message]

  facepalm:
    description: Broadcasts your facepalm.
    usage: /<command>
    aliases: [fp, fpalm, facep]

  slap:
    description: Broadcasts you slapping another player.
    usage: /<command> [player]

  harm:
    description: Harms a player.
    usage: /<command> [player] [damage]

  starve:
    description: Lowers a player's hunger.
    usage: /<command> [player] [damage]
    aliases: [strv]

  banned:
    description: Returns if a player is banned.
    usage: /<command> [player]
    
  setarmor:
    description: Sets your armor to a certain type.
    usage: /<command> [material]
    aliases: [armor, sarmor]
    
  getip:
    description: Gets the IP of a user.
    usage: /<command> [player]
    aliases: [getaddr, gip]
    
  compareip:
    description: Compare two users' IP addresses.
    usage: /<command> [player1] [player2]
    aliases: [compip, cip]
  
  ragequit:
    description: Ragequits yourself or another player.
    usage: /<command> (player)
    aliases: [rage, rq]
    
  quit:
    description: Makes yourself quit.
    usage: /<command>
    
  rank:
    description: Check the rank of the specified player (permissions).
    usage: /<command> [player]
    
  freeze:
    description: Freezes the player.
    usage: /<command> [player]
    aliases: [fz, frz]
    
  fakeop:
    description: Fakes an "You are now op!" message.
    usage: /<command> [player]
    aliases: [fop]
    
  vtp:
    description: Teleports to anyone, regardless of being vanished or having teleport off.
    usage: /<command> [player]
    
  vtphere:
    description: Teleports anyone you, regardless of being vanished or having teleport off.
    usage: /<command> [player]
    
  megastrike:
    description: Strikes lightning 15 times at the player's cursor or at specified player.
    usage: /<command> (player)
    aliases: [mstrike, megasmite, msmite, ms]
    
  pext:
    description: Extinguishes yourself or a player.
    usage: /<command> (player)
    aliases: [playerext, pex, splash]
    
  item:
    description: Add an item to your inventory.
    usage: /<command> [item](:metadata) (amount)
    aliases: [i]
    
  clearinventory:
    description: Clear you inventory.
    usage: /<command> (user)
    aliases: [ci, clearinv]
    
  weather:
    description: Changes the weather.
    usage: /<command> [conditions] (seconds)
    
  fixchunk:
    description: Fixes a voided chunk by reloading it.
    usage: /<command>
    aliases: [fc, fixc, cfix]
    
  give:
    description: Gives a player items.
    usage: /<command> [player] [item](:metadata) (amount)
    aliases: [g]
    
  message:
    description: Send a message to a player.
    usage: /<command> [player] [message]
    aliases: [msg, m, send, tell, whisper]
    
  reply:
    description: Reply to a message.
    usage: /<command> [message]
    aliases: [r]
    
  gamemode:
    description: Toggles your gamemode.
    usage: /<command>
    aliases: [gm, gamem, gmode]
    
  ban:
    description: Bans a user.
    usage: /<command> [player] (message)
    aliases: [rban]
    
  mute:
    description: Stop a user from speaking.
    usage: /<command> [player]
    aliases: [silence]
    
  kick:
    description: Kicks a player from the server.
    usage: /<command> [player] (message)
    aliases: [boot]
    
  time:
    description: Sets the time of your current world.
    usage: /<command> [ticks] (world)
    
  home:
    description: Teleports the player home.
    usage: /<command> (home)
    
  sethome:
    description: Sets the player's home.
    usage: /<command> (home)
    aliases: [shome]
    
  delhome:
    description: Deletes a home.
    usage: /<command> [home]
    aliases: [dhome, rmhome]
    
  listhome:
    description: List your set homes.
    usage: /<command>
    aliases: [lshome, listhomes, lshomes]
  
  strike:
    description: Strikes lightning at the player's cursor or at specified player.
    usage: /<command> (player)
    aliases: [smite]
    
  jump:
    description: Moves the player to the block they are looking at.
    usage: /<command>
    aliases: [j, tps, go]
        
  rcmds:
    description: Displays version of RoyalCommands.
    usage: /<command>
    
permissions:
  rcmds.*:
    description: Gives access to all RoyalCommands commands.
    children:
      rcmds.level: true
      rcmds.setlevel: true
      rcmds.sci: true
      rcmds.speak: true
      rcmds.facepalm: true
      rcmds.slap: true
      rcmds.harm: true
      rcmds.starve: true
      rcmds.banned: true
      rcmds.setarmor: true
      rcmds.getip: true
      rcmds.compareip: true
      rcmds.ragequit: true
      rcmds.quit: true
      rcmds.rcmds: true
  rcmds.exempt:
    description: Gives the exempt permission for every command.
    children:
      rcmds.sci.exempt: true
      rcmds.speak.exempt: true
      rcmds.facepalm.exempt: true
      rcmds.slap.exempt: true
      rcmds.harm.exempt: true
      rcmds.starve.exempt: true
  rcmds.level:
    description: Allows you to level your XP up by 1
    default: op
  rcmds.setlevel:
    description: Allows you to set your XP level
    default: op
  rcmds.sci:
    description: Allows you to selectively clear inventories
    default: op
  rcmds.speak:
    description: Allows you to spoof a message
    default: op
  rcmds.facepalm:
    description: Allows you to facepalm
    default: op
  rcmds.slap:
    description: Allows you to slap another player
    default: op
  rcmds.harm:
    description: Allows you to damage another player
    default: op
  rcmds.starve:
    description: Allows you to starve another player
    default: op
  rcmds.banned:
    description: Allows you to check if a player is banned
    default: op
  rcmds.setarmor:
    description: Allows you to set your armor
    default: op
  rcmds.getip:
    description: Allows you to get the IP of another player
    default: op
  rcmds.compareip:
    description: Allows you to compare to players' IPs
    default: op
  rcmds.ragequit:
    description: Allows you to ragequit.
    default: op
  rcmds.quit:
    description: Allows you to quit.
    default: op
  rcmds.rank:
    description: Allows you to check the rank of a player.
    default: op
  rcmds.freeze:
    description: Allows you to freeze a player.
    default: op
  rcmds.fakeop:
    description: Allows you to fake op.
    default: op
  rcmds.vtp:
    description: Allows you to override teleport.
    default: op
  rcmds.megastrike:
    description: Allows you to call a mega-strike.
    default: op
  rcmds.pext:
    description: Allows you to extinguish players.
    default: op
  rcmds.rcmds:
    description: Allows you to reload RoyalCommands' config
    default: op