# Credit to https://github.com/APDevTeam/Movecraft/actions for this
name: Maven Build

on: [push, pull_request]

jobs:
  # Build 1.19.4 NMS
  nms_version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Set up JDK 17 # 1.19.4 can only be built with Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache 1.19.4 Maven package
        id: cacheWild
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/
            ~/.m2/repository/org/spigotmc/spigot-parent/
            ~/.m2/repository/org/spigotmc/minecraft-server/
          key: ${{ runner.os }}-spigot-1.19.4-all
          restore-keys: ${{ runner.os }}-spigot-1.19.4-all
      - name: Cache Maven packages
        id: cacheMain
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2_1.19.4
          restore-keys: ${{ runner.os }}-m2_1.19.4

      - name: Setup BuildTools
        run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Check 1.19.4 Spigot
        id: wild
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19.4 Spigot (Mojang)
        id: wildMojang
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Check 1.19.4 Spigot (Obf)
        id: wildObf
        run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/spigot-1.19.4-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
      - name: Build 1.19.4
        if: steps.wild.outputs.sucess != 'true' || steps.wildMojang.outputs.sucess != 'true' || steps.wildObf.outputs.sucess != 'true'
        run: cd BuildTools && java -jar BuildTools.jar --rev 1.19.4 --compile craftbukkit --compile-if-changed


  # Build RoyalCommands using Maven
  build-rcmds:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    needs: nms_version

    steps:
    - name: Checkout RoyalCommands
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache 1.19.4 Maven package
      id: cacheWild
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository/org/spigotmc/spigot/1.19.4-R0.1-SNAPSHOT/
          ~/.m2/repository/org/spigotmc/spigot-parent/
          ~/.m2/repository/org/spigotmc/minecraft-server/
        key: ${{ runner.os }}-spigot-1.19.4-all
        restore-keys: ${{ runner.os }}-spigot-1.19.4-all

    - name: Cache Maven packages
      id: cacheMain
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2_1.19.4
        restore-keys: ${{ runner.os }}-m2_1.19.4

    - name: Build RoyalCommands with Maven
      env:
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: mvn clean package --settings settings.xml

    - uses: actions/upload-artifact@v3
      with:
        name: RoyalCommands (#${{ github.run_number }})
        path: /home/runner/work/RoyalCommands/RoyalCommands/modules/RoyalCommands/target/*.jar
